<?php

declare(strict_types=1);

namespace Mypos\Services;

use DateTimeImmutable;
use Mypos\Config\Database;
use Mypos\Core\HttpException;
use Mypos\Repositories\MyposCercaRepository;
use PDO;
use Throwable;

final class MyposCercaService
{
    private MyposCercaRepository $repository;
    public function __construct(?MyposCercaRepository $repository=null){$this->repository=$repository??new MyposCercaRepository(Database::connection());}

    public function profile(int $empresaId,int $sucursalId): array
    {
        $this->positive($empresaId,'empresa_id');$this->positive($sucursalId,'sucursal_id');
        return ['perfil'=>$this->repository->profile($empresaId,$sucursalId)];
    }

    public function saveProfile(int $userId,int $empresaId,int $sucursalId,array $payload): array
    {
        $name=trim((string)($payload['nombre_publico']??''));if($name===''||mb_strlen($name)>190)throw new HttpException('Nombre publico obligatorio',422);
        $lat=$this->coordinate($payload['latitud']??null,-90,90,'latitud');$lng=$this->coordinate($payload['longitud']??null,-180,180,'longitud');
        $tipo=strtoupper((string)($payload['anticipo_tipo']??'PORCENTAJE'));if(!in_array($tipo,['PORCENTAJE','MONTO'],true))throw new HttpException('Tipo de anticipo invalido',422);
        $valor=max(1,(int)($payload['anticipo_valor']??30));if($tipo==='PORCENTAJE'&&$valor>100)throw new HttpException('El porcentaje de anticipo no puede superar 100',422);
        $existing=$this->repository->profile($empresaId,$sucursalId);$slug=$existing['slug']??$this->slug($name).'-'.bin2hex(random_bytes(3));
        $data=['empresa_id'=>$empresaId,'sucursal_id'=>$sucursalId,'slug'=>$slug,'nombre_publico'=>$name,'descripcion'=>$this->nullable($payload['descripcion']??null,2000),'categoria'=>$this->nullable($payload['categoria']??null,100),'logo_url'=>$this->safeUrl($payload['logo_url']??null),'portada_url'=>$this->safeUrl($payload['portada_url']??null),'telefono_publico'=>$this->nullable($payload['telefono_publico']??null,40),'whatsapp'=>$this->nullable($payload['whatsapp']??null,40),'direccion_publica'=>$this->nullable($payload['direccion_publica']??null,255),'comuna'=>$this->nullable($payload['comuna']??null,100),'ciudad'=>$this->nullable($payload['ciudad']??null,100),'latitud'=>$lat,'longitud'=>$lng,'permite_retiro'=>$this->flag($payload['permite_retiro']??true),'permite_despacho'=>$this->flag($payload['permite_despacho']??false),'permite_cotizaciones'=>$this->flag($payload['permite_cotizaciones']??true),'permite_reservas'=>$this->flag($payload['permite_reservas']??false),'anticipo_tipo'=>$tipo,'anticipo_valor'=>$valor,'permite_pago_superior'=>$this->flag($payload['permite_pago_superior']??true),'reserva_expira_minutos'=>max(5,min(120,(int)($payload['reserva_expira_minutos']??15))),'publicado'=>$this->flag($payload['publicado']??false),'cerrado_temporalmente'=>$this->flag($payload['cerrado_temporalmente']??false),'privacidad_json'=>json_encode($payload['privacidad']??new \stdClass(),JSON_UNESCAPED_UNICODE)];
        if($data['publicado']===1&&($lat===null||$lng===null))throw new HttpException('Ubicacion obligatoria para publicar el local',422);
        $db=$this->repository->connection();try{$db->beginTransaction();$id=$this->repository->upsertProfile($data);$this->repository->replaceHours($empresaId,$id,$this->hours($payload['horarios']??[]));AuditoriaService::registrarEvento(['empresa_id'=>$empresaId,'sucursal_id'=>$sucursalId,'usuario_id'=>$userId,'modulo'=>'presencia_digital','accion'=>'configurar_perfil','entidad'=>'presencia_digital_perfiles','entidad_id'=>$id,'descripcion'=>'Perfil publico actualizado'], $db);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}
        return $this->profile($empresaId,$sucursalId);
    }

    public function products(int $empresaId,?int $sucursalId): array{return['productos'=>$this->repository->products($empresaId,$sucursalId)];}

    public function saveProducts(int $userId,int $empresaId,array $payload): array
    {
        $sucursalId=(int)($payload['sucursal_id']??0);$this->positive($sucursalId,'sucursal_id');$items=$payload['productos']??null;if(!is_array($items)||$items===[]||count($items)>1000)throw new HttpException('Productos obligatorios (maximo 1000)',422);
        $db=$this->repository->connection();try{$db->beginTransaction();foreach($items as $item){if(!is_array($item))continue;$productoId=(int)($item['producto_id']??0);$this->positive($productoId,'producto_id');$name=$this->nullable($item['nombre_publico']??null,190);$slug=(string)($item['slug']??'');if($slug==='')$slug=$this->slug($name?:'producto').'-'.bin2hex(random_bytes(4));$reg=strtoupper((string)($item['regulacion']??'VENTA_DIRECTA'));if(!in_array($reg,['VENTA_DIRECTA','SOLO_INFORMATIVO','RESTRINGIDO','NO_PUBLICAR'],true))throw new HttpException('Regulacion de producto invalida',422);$published=$reg==='NO_PUBLICAR'?0:$this->flag($item['publicado']??false);$allowsReservation=$reg==='VENTA_DIRECTA'?$this->flag($item['permite_reserva']??false):0;$this->repository->upsertProduct(['empresa_id'=>$empresaId,'sucursal_id'=>$sucursalId,'producto_id'=>$productoId,'slug'=>$slug,'nombre_publico'=>$name,'descripcion_publica'=>$this->nullable($item['descripcion_publica']??null,5000),'imagen_url'=>$this->safeUrl($item['imagen_url']??null),'palabras_busqueda'=>$this->nullable($item['palabras_busqueda']??null,500),'categoria_publica'=>$this->nullable($item['categoria_publica']??null,100),'mostrar_precio'=>$this->flag($item['mostrar_precio']??true),'precio_online'=>isset($item['precio_online'])&&$item['precio_online']!==''?max(0,(int)$item['precio_online']):null,'stock_protegido'=>number_format(max(0,(float)($item['stock_protegido']??0)),3,'.',''),'mostrar_agotado'=>$this->flag($item['mostrar_agotado']??false),'permite_cotizacion'=>$reg==='RESTRINGIDO'?0:$this->flag($item['permite_cotizacion']??true),'permite_reserva'=>$allowsReservation,'exige_pago_total'=>$this->flag($item['exige_pago_total']??false),'regulacion'=>$reg,'publicado'=>$published]);}AuditoriaService::registrarEvento(['empresa_id'=>$empresaId,'sucursal_id'=>$sucursalId,'usuario_id'=>$userId,'modulo'=>'presencia_digital','accion'=>'publicacion_masiva','entidad'=>'presencia_digital_productos','descripcion'=>'Configuracion publica de productos actualizada','metadata'=>['cantidad'=>count($items)]],$db);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
        return $this->products($empresaId,$sucursalId);
    }

    public function search(array $filters,string $session): array
    {
        $q=trim((string)($filters['q']??''));if(mb_strlen($q)<2||mb_strlen($q)>100)throw new HttpException('Busqueda entre 2 y 100 caracteres',422);$lat=$this->coordinate($filters['lat']??null,-90,90,'lat');$lng=$this->coordinate($filters['lng']??null,-180,180,'lng');$rows=$this->repository->search($q,$lat,$lng,max(1,min(100,(int)($filters['limit']??30))));foreach($rows as &$r){$this->repository->metric((int)$r['empresa_id'],(int)$r['sucursal_id'],(int)$r['producto_id'],'BUSQUEDA',$session,['q'=>mb_substr($q,0,100)]);unset($r['empresa_id'],$r['sucursal_id'],$r['producto_id']);}unset($r);return['resultados'=>$rows,'total'=>count($rows)];
    }

    public function store(string $slug,string $session): array
    {
        $p=$this->repository->profileBySlug($slug);if($p===null)throw new HttpException('Local no encontrado',404);$this->repository->metric((int)$p['empresa_id'],(int)$p['sucursal_id'],null,'VISITA_LOCAL',$session);return['local'=>$this->sanitizeProfile($p),'productos'=>$this->repository->publishedProductsForStore((int)$p['empresa_id'],(int)$p['sucursal_id'])];
    }

    public function product(string $slug,string $session): array
    {
        $p=$this->repository->publicProduct($slug);if($p===null)throw new HttpException('Producto no encontrado',404);$this->repository->metric((int)$p['empresa_id'],(int)$p['sucursal_id'],(int)$p['producto_id'],'VISITA_PRODUCTO',$session);$available=max(0,(float)$p['cantidad']-(float)$p['reservado']-(float)$p['stock_protegido']);$p['disponibilidad']=$available<=0?'AGOTADO':($available<=1?'POCAS_UNIDADES':'DISPONIBLE');unset($p['cantidad'],$p['reservado'],$p['stock_protegido']);return['producto'=>$p];
    }

    public function createQuote(array $payload,string $session): array
    {
        $profile=$this->repository->profileBySlug(trim((string)($payload['local_slug']??'')));if($profile===null||(int)$profile['permite_cotizaciones']!==1)throw new HttpException('El local no acepta cotizaciones',422);$contact=$this->contact($payload);$items=$this->resolveItems($payload,(int)$profile['empresa_id'],(int)$profile['sucursal_id'],'cotizacion');$data=['empresa_id'=>(int)$profile['empresa_id'],'sucursal_id'=>(int)$profile['sucursal_id'],'codigo'=>'CQ-'.strtoupper(bin2hex(random_bytes(6))),'nombre_cliente'=>$contact['nombre'],'email_cliente'=>$contact['email'],'telefono_cliente'=>$contact['telefono'],'mensaje'=>$this->nullable($payload['mensaje']??null,500),'expires_at'=>(new DateTimeImmutable('+7 days'))->format('Y-m-d H:i:s')];$db=$this->repository->connection();try{$db->beginTransaction();$id=$this->repository->insertQuote($data,$items);$this->repository->metric((int)$profile['empresa_id'],(int)$profile['sucursal_id'],null,'COTIZACION',$session);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return['solicitud_id'=>$id,'codigo'=>$data['codigo'],'estado'=>'SOLICITADA'];
    }

    public function createReservation(array $payload,string $session): array
    {
        $idempotency=trim((string)($payload['idempotency_key']??''));if(strlen($idempotency)<16||strlen($idempotency)>100)throw new HttpException('idempotency_key invalida',422);$profile=$this->repository->profileBySlug(trim((string)($payload['local_slug']??'')));if($profile===null||(int)$profile['permite_reservas']!==1)throw new HttpException('El local no acepta reservas',422);$contact=$this->contact($payload);$resolved=$this->resolveItems($payload,(int)$profile['empresa_id'],(int)$profile['sucursal_id'],'reserva');$subtotal=0;$mustFull=false;foreach($resolved as$r){$subtotal+=(int)$r['precio_snapshot']*(float)$r['cantidad'];$mustFull=$mustFull||(int)$r['exige_pago_total']===1;}if($subtotal<=0)throw new HttpException('La reserva debe tener un total mayor que cero',422);$subtotal=(int)round($subtotal);$minimum=$mustFull?$subtotal:((string)$profile['anticipo_tipo']==='MONTO'?min($subtotal,(int)$profile['anticipo_valor']):(int)ceil($subtotal*(int)$profile['anticipo_valor']/100));$minimum=max(1,$minimum);$token=bin2hex(random_bytes(24));$expires=(new DateTimeImmutable('+'.max(5,min(120,(int)$profile['reserva_expira_minutos'])).' minutes'))->format('Y-m-d H:i:s');$db=$this->repository->connection();$stock=new StockService();try{$db->beginTransaction();$items=[];foreach($resolved as$r){$reserved=$stock->reservarParaCanalDigital((int)$profile['empresa_id'],(int)$profile['sucursal_id'],(int)$r['producto_id'],(float)$r['cantidad'],(float)$r['stock_protegido'],$db);$items[]=['empresa_id'=>(int)$profile['empresa_id'],'producto_id'=>(int)$r['producto_id'],'ubicacion_id'=>(int)$reserved['ubicacion_id'],'cantidad'=>$r['cantidad'],'precio_unitario'=>(int)$r['precio_snapshot'],'nombre_snapshot'=>$r['nombre_snapshot']];}$id=$this->repository->insertReservation(['empresa_id'=>(int)$profile['empresa_id'],'sucursal_id'=>(int)$profile['sucursal_id'],'codigo'=>'R-'.strtoupper(bin2hex(random_bytes(6))),'token_hash'=>hash('sha256',$token),'idempotency_key'=>$idempotency,'nombre_cliente'=>$contact['nombre'],'email_cliente'=>$contact['email'],'telefono_cliente'=>$contact['telefono'],'subtotal'=>$subtotal,'anticipo_minimo'=>$minimum,'subtotal_saldo'=>$subtotal,'expires_at'=>$expires],$items);$this->repository->metric((int)$profile['empresa_id'],(int)$profile['sucursal_id'],null,'RESERVA_INICIADA',$session);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return['reserva_id'=>$id,'token'=>$token,'estado'=>'PENDIENTE_PAGO','subtotal'=>$subtotal,'anticipo_minimo'=>$minimum,'monto_maximo'=>$subtotal,'permite_pago_superior'=>(int)$profile['permite_pago_superior'],'expires_at'=>$expires];
    }

    public function reservationStatus(string $token): array { if(!preg_match('/^[a-f0-9]{48}$/',$token))throw new HttpException('Reserva no encontrada',404);$r=$this->repository->reservationByTokenHash(hash('sha256',$token));if($r===null)throw new HttpException('Reserva no encontrada',404);unset($r['id'],$r['empresa_id'],$r['sucursal_id'],$r['token_hash'],$r['idempotency_key']);foreach($r['items'] as &$i){unset($i['id'],$i['empresa_id'],$i['reserva_id'],$i['producto_id'],$i['ubicacion_id'],$i['reserva_liberada']);}return['reserva'=>$r]; }
    public function quotes(int $empresaId): array{return['cotizaciones'=>$this->repository->listQuotes($empresaId)];}
    public function reservations(int $empresaId): array{return['reservas'=>$this->repository->listReservations($empresaId)];}
    public function metrics(int $empresaId,int $days): array{return['dias'=>$days]+$this->repository->metrics($empresaId,max(1,min(365,$days)));}

    public function changeReservationState(int $userId,int $empresaId,int $id,string $state):array
    {
        $state=strtoupper(trim($state));$allowed=['CONFIRMADA','PREPARANDO','LISTA_RETIRO','CANCELADA'];if(!in_array($state,$allowed,true))throw new HttpException('Estado de reserva invalido',422);$db=$this->repository->connection();try{$db->beginTransaction();$r=$this->repository->reservation($empresaId,$id,true);if($r===null)throw new HttpException('Reserva no encontrada',404);$current=(string)$r['estado'];$valid=['PAGO_CONFIRMADO'=>['CONFIRMADA','CANCELADA'],'CONFIRMADA'=>['PREPARANDO','CANCELADA'],'PREPARANDO'=>['LISTA_RETIRO','CANCELADA'],'LISTA_RETIRO'=>['CANCELADA']];if(!in_array($state,$valid[$current]??[],true))throw new HttpException("Transicion {$current} a {$state} no permitida",409);if($state==='CANCELADA'&&(int)$r['pagado']>0)throw new HttpException('La reserva pagada requiere reembolso antes de liberar stock',409);if($state==='CANCELADA')$this->releaseReservationItems($r,$db);$this->repository->updateReservationState($empresaId,$id,$state);$this->repository->reservationEvent($empresaId,$id,'ESTADO_CAMBIADO',['desde'=>$current,'hasta'=>$state,'usuario_id'=>$userId]);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}return['reserva_id'=>$id,'estado'=>$state];
    }

    public function cancelAfterRefund(int $userId,int $empresaId,int $id):array
    {
        $db=$this->repository->connection();try{$db->beginTransaction();$r=$this->repository->reservation($empresaId,$id,true);if($r===null)throw new HttpException('Reserva no encontrada',404);if(!in_array((string)$r['estado'],['PAGO_CONFIRMADO','CONFIRMADA','PREPARANDO','LISTA_RETIRO'],true))throw new HttpException('La reserva no admite cancelacion',409);$this->repository->clearReservationPaid($empresaId,$id);$this->releaseReservationItems($r,$db);$this->repository->updateReservationState($empresaId,$id,'CANCELADA');$this->repository->reservationEvent($empresaId,$id,'ESTADO_CAMBIADO',['desde'=>$r['estado'],'hasta'=>'CANCELADA','usuario_id'=>$userId,'motivo'=>'reembolso_confirmado']);$db->commit();return['reserva_id'=>$id,'estado'=>'CANCELADA'];}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
    }

    public function convertReservationToSale(int $userId,int $empresaId,int $id,array $payload):array
    {
        $r=$this->repository->reservation($empresaId,$id);if($r===null)throw new HttpException('Reserva no encontrada',404);if(!in_array((string)$r['estado'],['PAGO_CONFIRMADO','CONFIRMADA','PREPARANDO','LISTA_RETIRO'],true))throw new HttpException('La reserva no puede convertirse a venta',409);$onlineRepo=new \Mypos\Repositories\OnlinePaymentRepository($this->repository->connection());$online=$onlineRepo->approvedForReservation($empresaId,$id);$payments=[];$onlineTotal=0;foreach($online as$p){$amount=(int)$p['monto'];$onlineTotal+=$amount;$payments[]=['metodo_pago_codigo'=>$p['proveedor']==='FLOW'?'FLOW_ONLINE':'MP_ONLINE','monto'=>$amount,'referencia'=>$p['referencia']];}$balance=(int)$r['subtotal']-$onlineTotal;$cash=$payload['pagos_saldo']??[];if($balance>0){if(!is_array($cash)||$cash===[])throw new HttpException('Debe registrar el pago del saldo pendiente',422);foreach($cash as$p){if(!is_array($p))continue;$payments[]=$p;}}$items=array_map(fn($i)=>['producto_id'=>(int)$i['producto_id'],'nombre'=>$i['nombre_snapshot'],'cantidad'=>(float)$i['cantidad'],'precio_unit'=>(int)$i['precio_unitario']],$r['items']);$sale=(new VentaService())->registrarVenta($userId,['empresa_id'=>$empresaId,'sucursal_id'=>(int)$r['sucursal_id'],'presencia_reserva_id'=>$id,'tipo_venta'=>$payload['tipo_venta']??'BOLETA','condicion_pago'=>'CONTADO','items'=>$items,'pagos'=>$payments,'origen'=>'ONLINE']);$saleId=(int)($sale['venta_id']??0);if($saleId<=0)throw new HttpException('No se pudo convertir la reserva',500);$this->repository->linkReservationSale($empresaId,$id,$saleId);$this->repository->reservationEvent($empresaId,$id,'CONVERTIDA_VENTA',['venta_id'=>$saleId,'usuario_id'=>$userId]);return['reserva_id'=>$id,'venta_id'=>$saleId,'estado'=>'RETIRADA']+$sale;
    }

    public function expireReservations(int $limit=100):array
    {
        $rows=$this->repository->expiredReservations(max(1,min(500,$limit)));$expired=0;foreach($rows as$row){$db=$this->repository->connection();try{$db->beginTransaction();$r=$this->repository->reservation((int)$row['empresa_id'],(int)$row['id'],true);if($r===null||(string)$r['estado']!=='PENDIENTE_PAGO'){if($db->inTransaction())$db->rollBack();continue;}$this->releaseReservationItems($r,$db);$this->repository->updateReservationState((int)$r['empresa_id'],(int)$r['id'],'VENCIDA');$this->repository->reservationEvent((int)$r['empresa_id'],(int)$r['id'],'VENCIDA');$db->commit();$expired++;}catch(Throwable$e){if($db->inTransaction())$db->rollBack();error_log('[MyposCerca][expire] '.$e->getMessage());}}return['procesadas'=>count($rows),'vencidas'=>$expired];
    }

    private function resolveItems(array $payload,int $empresaId,int $sucursalId,string $mode): array { $raw=$payload['items']??null;if(!is_array($raw)||$raw===[]||count($raw)>50)throw new HttpException('Items obligatorios (maximo 50)',422);$ids=[];foreach($raw as$i)if(is_array($i))$ids[]=(int)($i['producto_id']??0);$catalog=$this->repository->publicItems($ids,$empresaId,$sucursalId);$out=[];foreach($raw as$i){if(!is_array($i))continue;$id=(int)($i['producto_id']??0);$qty=(float)($i['cantidad']??0);if($qty<=0||$qty>9999||!isset($catalog[$id]))throw new HttpException('Producto o cantidad invalida',422);$p=$catalog[$id];if($mode==='reserva'&&(int)$p['permite_reserva']!==1)throw new HttpException('Un producto no permite reserva',422);if($mode==='cotizacion'&&(int)$p['permite_cotizacion']!==1)throw new HttpException('Un producto no permite cotizacion',422);$out[]=['empresa_id'=>$empresaId,'producto_id'=>$id,'cantidad'=>number_format($qty,3,'.',''),'nombre_snapshot'=>(string)$p['nombre'],'precio_snapshot'=>(int)$p['precio'],'stock_protegido'=>(float)$p['stock_protegido'],'exige_pago_total'=>(int)$p['exige_pago_total']];}return$out; }
    private function releaseReservationItems(array $reservation,PDO $db):void{$stock=new StockService();foreach($reservation['items']as$item){if((int)$item['reserva_liberada']===1)continue;$stock->liberarReservaDigital((int)$reservation['empresa_id'],(int)$reservation['sucursal_id'],(int)$item['producto_id'],(int)$item['ubicacion_id'],(float)$item['cantidad'],$db);$this->repository->markReservationItemReleased((int)$item['id']);}}
    private function contact(array $p): array { $name=trim((string)($p['nombre_cliente']??''));$email=strtolower(trim((string)($p['email_cliente']??'')));if($name===''||mb_strlen($name)>160||filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new HttpException('Nombre y correo validos son obligatorios',422);return['nombre'=>$name,'email'=>$email,'telefono'=>$this->nullable($p['telefono_cliente']??null,40)]; }
    private function hours(mixed $raw): array { if(!is_array($raw))return[];$out=[];$seen=[];foreach($raw as$h){if(!is_array($h))continue;$day=(int)($h['dia_semana']??-1);if($day<0||$day>6||isset($seen[$day]))throw new HttpException('Horario invalido',422);$seen[$day]=1;$closed=$this->flag($h['cerrado']??false);$open=$closed?null:$this->time($h['apertura']??null);$close=$closed?null:$this->time($h['cierre']??null);if(!$closed&&($open===null||$close===null||$open>=$close))throw new HttpException('Horario de apertura/cierre invalido',422);$out[]=['dia_semana'=>$day,'apertura'=>$open,'cierre'=>$close,'cerrado'=>$closed];}return$out; }
    private function sanitizeProfile(array $p): array { unset($p['id'],$p['empresa_id'],$p['sucursal_id'],$p['privacidad_json']);return$p; }
    private function safeUrl(mixed $v): ?string { $s=$this->nullable($v,500);if($s===null)return null;if(str_starts_with($s,'/'))return$s;if(filter_var($s,FILTER_VALIDATE_URL)===false||!str_starts_with(strtolower($s),'https://'))throw new HttpException('URL publica invalida',422);return$s; }
    private function coordinate(mixed $v,float $min,float $max,string $field): ?float { if($v===null||$v==='')return null;if(!is_numeric($v)||(float)$v<$min||(float)$v>$max)throw new HttpException($field.' invalida',422);return(float)$v; }
    private function nullable(mixed $v,int $max): ?string { $s=trim((string)$v);if($s==='')return null;if(mb_strlen($s)>$max)throw new HttpException('Texto demasiado largo',422);return$s; }
    private function flag(mixed $v): int{return filter_var($v,FILTER_VALIDATE_BOOLEAN)?1:0;}
    private function time(mixed $v): ?string{$s=trim((string)$v);return preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/',$s)?substr($s,0,5):null;}
    private function slug(string $s): string{$s=iconv('UTF-8','ASCII//TRANSLIT',$s)?:$s;$s=strtolower(preg_replace('/[^a-zA-Z0-9]+/','-',$s)??'');return trim($s,'-')?:'local';}
    private function positive(int $v,string $f):void{if($v<=0)throw new HttpException($f.' obligatorio',422);}
}
