<?php

declare(strict_types=1);

namespace Mypos\Services;

use DateTimeImmutable;
use Mypos\Config\Database;
use Mypos\Core\HttpException;
use Mypos\Repositories\MyposCercaRepository;
use Mypos\Repositories\OnlinePaymentRepository;
use Mypos\Services\Payments\PaymentGatewayFactory;
use Mypos\Support\Crypto;
use Mypos\Support\Env;
use PDO;
use Throwable;

final class OnlinePaymentService
{
    private OnlinePaymentRepository $payments;private MyposCercaRepository $cerca;
    public function __construct(?OnlinePaymentRepository $payments=null,?MyposCercaRepository $cerca=null){$db=Database::connection();$this->payments=$payments??new OnlinePaymentRepository($db);$this->cerca=$cerca??new MyposCercaRepository($db);}

    public function confirmForSale(PDO $db,int $empresaId,string $reference,int $amount,int $saleId):void
    {
        $repo=new OnlinePaymentRepository($db);$intent=$repo->intentByReference($reference,true);
        if($intent===null||(int)$intent['empresa_id']!==$empresaId)throw new HttpException('Pago online no encontrado para esta empresa',422);
        if((string)$intent['estado']!=='APROBADO')throw new HttpException('El pago online aun no esta aprobado',409);
        if((int)$intent['monto']!==$amount)throw new HttpException('El monto del pago online no coincide',409);
        if(!empty($intent['consumed_at'])||!empty($intent['venta_id']))throw new HttpException('El pago online ya fue utilizado en otra venta',409);
        $repo->updateIntent((int)$intent['id'],['venta_id'=>$saleId,'consumed_at'=>date('Y-m-d H:i:s')]);
    }

    public function refundReservation(int $userId,int $empresaId,int $reservationId):array
    {
        $reservation=$this->cerca->reservation($empresaId,$reservationId);if($reservation===null)throw new HttpException('Reserva no encontrada',404);if((int)$reservation['pagado']<=0)throw new HttpException('La reserva no tiene pagos para reembolsar',409);if(!empty($reservation['venta_id']))throw new HttpException('La reserva ya fue convertida a venta; usa el flujo de anulación',409);
        $intents=$this->payments->approvedForReservation($empresaId,$reservationId);if($intents===[])throw new HttpException('No hay pagos aprobados para reembolsar',409);$pending=false;$refunded=0;
        foreach($intents as$intent){if(empty($intent['proveedor_id']))throw new HttpException('Pago sin identificador de pasarela',409);$config=$this->requiredConfig($empresaId,(string)$intent['proveedor']);$result=PaymentGatewayFactory::fromConfig($config)->refund((string)$intent['proveedor_id'],(int)$intent['monto']);$state=(string)($result['status']??'REEMBOLSO_PENDIENTE');$this->payments->updateIntent((int)$intent['id'],['estado'=>$state,'raw_status_json'=>json_encode($result['raw']??[],JSON_UNESCAPED_UNICODE)]);$pending=$pending||$state!=='REEMBOLSADO';$refunded+=(int)$intent['monto'];}
        if(!$pending)(new MyposCercaService())->cancelAfterRefund($userId,$empresaId,$reservationId);
        AuditoriaService::registrarEvento(['empresa_id'=>$empresaId,'usuario_id'=>$userId,'modulo'=>'presencia_digital','accion'=>'reembolsar_reserva','entidad'=>'presencia_reservas','entidad_id'=>$reservationId,'descripcion'=>'Reembolso solicitado a las pasarelas','metadata'=>['monto'=>$refunded,'pendiente'=>$pending]]);
        return['reserva_id'=>$reservationId,'monto'=>$refunded,'estado'=>$pending?'REEMBOLSO_PENDIENTE':'REEMBOLSADA_Y_CANCELADA','stock_liberado'=>!$pending];
    }

    public function configs(int $empresaId):array
    {
        $out=[];foreach(['FLOW','MERCADOPAGO']as$p){$c=$this->payments->config($empresaId,$p);$v=$this->payments->verification($empresaId,$p);$out[]=['proveedor'=>$p,'configurado'=>$c!==null&&(!empty($c['secreto_cifrado'])||!empty($c['access_token_cifrado'])),'ambiente'=>$c['ambiente']??'sandbox','activo'=>(int)($c['activo']??0),'orden'=>(int)($c['orden']??100),'merchant_id'=>$c['merchant_id']??null,'tiene_webhook_secret'=>!empty($c['webhook_secret_cifrado']),'verificacion'=>$v];}return['pasarelas'=>$out];
    }

    public function saveConfig(int $userId,int $empresaId,string $provider,array $data):array
    {
        $provider=$this->provider($provider);$environment=strtolower(trim((string)($data['ambiente']??'sandbox')));if(!in_array($environment,['sandbox','produccion'],true))throw new HttpException('Ambiente invalido',422);$existing=$this->payments->config($empresaId,$provider);
        $apiKey=$provider==='FLOW'?trim((string)($data['api_key']??'')):null;$secret=$provider==='FLOW'?trim((string)($data['secret_key']??'')):'';$access=$provider==='MERCADOPAGO'?trim((string)($data['access_token']??'')):'';$webhook=trim((string)($data['webhook_secret']??''));
        if($existing===null&&(($provider==='FLOW'&&($apiKey===''||$secret===''))||($provider==='MERCADOPAGO'&&$access==='')))throw new HttpException('Credenciales obligatorias para conectar la pasarela',422);
        $this->payments->upsertConfig(['empresa_id'=>$empresaId,'proveedor'=>$provider,'ambiente'=>$environment,'credencial_publica'=>$apiKey!==''?$apiKey:null,'secreto_cifrado'=>$secret!==''?Crypto::encrypt($secret):null,'access_token_cifrado'=>$access!==''?Crypto::encrypt($access):null,'refresh_token_cifrado'=>null,'token_expires_at'=>null,'merchant_id'=>$this->nullable($data['merchant_id']??null,100),'webhook_secret_cifrado'=>$webhook!==''?Crypto::encrypt($webhook):null,'activo'=>$this->flag($data['activo']??false),'orden'=>max(1,min(999,(int)($data['orden']??100))),'metadata_json'=>json_encode(['configured_via'=>$provider==='MERCADOPAGO'?'manual_or_oauth':'api_keys'],JSON_UNESCAPED_UNICODE)]);
        AuditoriaService::registrarEvento(['empresa_id'=>$empresaId,'usuario_id'=>$userId,'modulo'=>'presencia_digital','accion'=>'configurar_pasarela','entidad'=>'pasarelas_pago_config','descripcion'=>'Pasarela de pago actualizada','metadata'=>['proveedor'=>$provider,'ambiente'=>$environment,'secreto_actualizado'=>$secret!==''||$access!=='']]);return$this->configs($empresaId);
    }

    public function validate(int $empresaId,string $provider):array
    {
        $provider=$this->provider($provider);$config=$this->requiredConfig($empresaId,$provider);$result=PaymentGatewayFactory::fromConfig($config)->validateCredentials();$this->payments->upsertVerification($empresaId,$provider,['credenciales_estado'=>$result['ok']?'VALIDAS':'INVALIDAS','credenciales_verified_at'=>$result['ok']?date('Y-m-d H:i:s'):null,'ultimo_error'=>$result['ok']?null:$result['message']]);return$result+['proveedor'=>$provider];
    }

    public function mercadoPagoOauthStart(int $userId,int $empresaId):array
    {
        $clientId=trim((string)Env::get('MP_MARKETPLACE_CLIENT_ID',''));$redirect=trim((string)Env::get('MP_MARKETPLACE_REDIRECT_URI',''));if($clientId===''||$redirect==='')throw new HttpException('OAuth de Mercado Pago no esta configurado en el servidor',503);$state=bin2hex(random_bytes(32));$this->payments->createOauthState($empresaId,$userId,'MERCADOPAGO',hash('sha256',$state),(new DateTimeImmutable('+10 minutes'))->format('Y-m-d H:i:s'));$url='https://auth.mercadopago.cl/authorization?'.http_build_query(['client_id'=>$clientId,'response_type'=>'code','platform_id'=>'mp','state'=>$state,'redirect_uri'=>$redirect]);return['authorization_url'=>$url,'expires_in'=>600];
    }

    public function mercadoPagoOauthComplete(string $state,string $code):array
    {
        if(!preg_match('/^[a-f0-9]{64}$/',$state)||$code==='')throw new HttpException('Respuesta OAuth invalida',422);$db=$this->payments->connection();try{$db->beginTransaction();$row=$this->payments->consumeOauthState('MERCADOPAGO',hash('sha256',$state));if($row===null)throw new HttpException('Autorizacion OAuth expirada o utilizada',409);$clientId=trim((string)Env::get('MP_MARKETPLACE_CLIENT_ID',''));$clientSecret=trim((string)Env::get('MP_MARKETPLACE_CLIENT_SECRET',''));$redirect=trim((string)Env::get('MP_MARKETPLACE_REDIRECT_URI',''));if($clientId===''||$clientSecret===''||$redirect==='')throw new HttpException('OAuth no configurado',503);$http=new \Mypos\Support\GatewayHttpClient();$response=$http->request('POST','https://api.mercadopago.com/oauth/token',['Accept: application/json','Content-Type: application/json'],json_encode(['client_id'=>$clientId,'client_secret'=>$clientSecret,'grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>$redirect],JSON_UNESCAPED_SLASHES));if($response['status']<200||$response['status']>=300||empty($response['body']['access_token']))throw new HttpException('Mercado Pago no autorizo la conexion',502);$body=$response['body'];$expires=isset($body['expires_in'])?(new DateTimeImmutable('+'.(int)$body['expires_in'].' seconds'))->format('Y-m-d H:i:s'):null;$this->payments->upsertConfig(['empresa_id'=>(int)$row['empresa_id'],'proveedor'=>'MERCADOPAGO','ambiente'=>'produccion','credencial_publica'=>null,'secreto_cifrado'=>null,'access_token_cifrado'=>Crypto::encrypt((string)$body['access_token']),'refresh_token_cifrado'=>!empty($body['refresh_token'])?Crypto::encrypt((string)$body['refresh_token']):null,'token_expires_at'=>$expires,'merchant_id'=>isset($body['user_id'])?(string)$body['user_id']:null,'webhook_secret_cifrado'=>null,'activo'=>0,'orden'=>100,'metadata_json'=>json_encode(['configured_via'=>'oauth'],JSON_UNESCAPED_UNICODE)]);$db->commit();return['conectado'=>true,'empresa_id'=>(int)$row['empresa_id'],'merchant_id'=>$body['user_id']??null,'requiere_validacion'=>true];}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
    }

    public function availableForPublic(int $empresaId):array{return['pasarelas'=>array_map(fn($c)=>['proveedor'=>$c['proveedor'],'nombre'=>$c['proveedor']==='FLOW'?'Flow':'Mercado Pago'], $this->payments->activeConfigs($empresaId))];}
    public function availableForReservation(string $token):array{if(!preg_match('/^[a-f0-9]{48}$/',$token))throw new HttpException('Reserva no encontrada',404);$r=$this->cerca->reservationByTokenHash(hash('sha256',$token));if($r===null)throw new HttpException('Reserva no encontrada',404);return$this->availableForPublic((int)$r['empresa_id']);}

    public function createReservationPayment(string $token,array $payload):array
    {
        if(!preg_match('/^[a-f0-9]{48}$/',$token))throw new HttpException('Reserva no encontrada',404);$reservation=$this->cerca->reservationByTokenHash(hash('sha256',$token));if($reservation===null)throw new HttpException('Reserva no encontrada',404);if((string)$reservation['estado']!=='PENDIENTE_PAGO'||strtotime((string)$reservation['expires_at'])<=time())throw new HttpException('La reserva ya no admite pagos',409);$amount=(int)($payload['monto']??0);$minimum=max((int)$reservation['anticipo_minimo']-(int)$reservation['pagado'],1);$maximum=(int)$reservation['saldo_pendiente'];if($amount<$minimum||$amount>$maximum)throw new HttpException('Monto fuera del rango permitido',422,['monto'=>["Debe estar entre {$minimum} y {$maximum}"]]);$provider=$this->provider((string)($payload['proveedor']??''));$config=$this->requiredConfig((int)$reservation['empresa_id'],$provider);if((int)$config['activo']!==1)throw new HttpException('Pasarela no disponible',422);$idempotency=trim((string)($payload['idempotency_key']??''));if(strlen($idempotency)<16||strlen($idempotency)>100)throw new HttpException('idempotency_key invalida',422);$reference='MC-'.strtoupper(bin2hex(random_bytes(8)));$db=$this->payments->connection();try{$db->beginTransaction();$id=$this->payments->insertIntent(['empresa_id'=>(int)$reservation['empresa_id'],'reserva_id'=>(int)$reservation['id'],'proveedor'=>$provider,'tipo'=>'RESERVA','idempotency_key'=>$idempotency,'referencia'=>$reference,'monto'=>$amount]);$base=rtrim((string)Env::get('APP_URL','https://mypos.cl'),'/');$created=PaymentGatewayFactory::fromConfig($config)->createPayment(['reference'=>$reference,'description'=>'Anticipo reserva '.(string)$reservation['codigo'],'amount'=>$amount,'payer_email'=>(string)$reservation['email_cliente'],'notification_url'=>$base.'/api/public/cerca/pagos/'.strtolower($provider).'/confirmacion?reference='.rawurlencode($reference),'return_url'=>$base.'/cerca/reserva/'.$token,'timeout_seconds'=>max(60,strtotime((string)$reservation['expires_at'])-time()),'idempotency_key'=>$idempotency]);$this->payments->updateIntent($id,['proveedor_id'=>(string)$created['provider_id'],'estado'=>'PENDIENTE','checkout_url'=>(string)$created['checkout_url'],'raw_status_json'=>json_encode($created['raw']??[],JSON_UNESCAPED_UNICODE)]);$this->cerca->reservationEvent((int)$reservation['empresa_id'],(int)$reservation['id'],'PAGO_CREADO',['intento_id'=>$id,'proveedor'=>$provider,'monto'=>$amount]);$db->commit();return['intento_id'=>$id,'estado'=>'PENDIENTE','checkout_url'=>$created['checkout_url'],'expires_at'=>$reservation['expires_at']];}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
    }

    public function handleCallback(string $provider,array $payload,array $headers=[]):array
    {
        $provider=$this->provider($provider);$providerId=$provider==='FLOW'?trim((string)($payload['flowOrder']??$payload['token']??'')):trim((string)($payload['data']['id']??$payload['id']??''));if($providerId==='')return['accepted'=>true,'pending'=>true];$reference=trim((string)($payload['reference']??''));$intent=$reference!==''?$this->payments->intentByReference($reference):$this->payments->intentByProviderId($provider,$providerId);if($intent===null||(string)$intent['proveedor']!==$provider)return['accepted'=>true,'matched'=>false];$eventKey=hash('sha256',$provider.'|'.$providerId.'|'.json_encode($payload));if(!$this->payments->addEvent($provider,$eventKey,(int)$intent['id'],$payload))return['accepted'=>true,'duplicate'=>true];$this->reconcileIntent($intent,$providerId);$this->payments->markEventProcessed($provider,$eventKey);return['accepted'=>true,'matched'=>true];
    }

    public function reconcile(int $limit=50):array{$rows=$this->payments->pendingForReconcile(max(1,min(100,$limit)));$ok=0;$failed=0;foreach($rows as$r){try{$this->reconcileIntent($r,(string)$r['proveedor_id']);$ok++;}catch(Throwable$e){$this->payments->updateIntent((int)$r['id'],['ultimo_error'=>mb_substr($e->getMessage(),0,500)]);$failed++;}}return['procesados'=>count($rows),'correctos'=>$ok,'fallidos'=>$failed];}

    public function createVerificationPayment(int $empresaId,string $provider,array $data):array{$amount=(int)($data['monto']??500);if($amount<500||$amount>5000)throw new HttpException('La prueba real debe estar entre $500 y $5.000',422);$email=strtolower(trim((string)($data['email_pagador']??'')));if(filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new HttpException('Correo del pagador invalido',422);$provider=$this->provider($provider);$config=$this->requiredConfig($empresaId,$provider);if((string)$config['ambiente']!=='produccion')throw new HttpException('La prueba real requiere ambiente de produccion',422);$reference='VERIFY-'.strtoupper(bin2hex(random_bytes(8)));$idempotency=trim((string)($data['idempotency_key']??''));if(strlen($idempotency)<16)$idempotency=bin2hex(random_bytes(16));$id=$this->payments->insertIntent(['empresa_id'=>$empresaId,'reserva_id'=>null,'proveedor'=>$provider,'tipo'=>'VERIFICACION','idempotency_key'=>$idempotency,'referencia'=>$reference,'monto'=>$amount]);$base=rtrim((string)Env::get('APP_URL','https://mypos.cl'),'/');$created=PaymentGatewayFactory::fromConfig($config)->createPayment(['reference'=>$reference,'description'=>'Verificacion de cobros MyPOS Cerca','amount'=>$amount,'payer_email'=>$email,'notification_url'=>$base.'/api/public/cerca/pagos/'.strtolower($provider).'/confirmacion?reference='.rawurlencode($reference),'return_url'=>$base.'/app/configuracion?payment_verification='.$id,'timeout_seconds'=>900,'idempotency_key'=>$idempotency]);$this->payments->updateIntent($id,['proveedor_id'=>(string)$created['provider_id'],'estado'=>'PENDIENTE','checkout_url'=>(string)$created['checkout_url']]);$this->payments->upsertVerification($empresaId,$provider,['pago_real_intento_id'=>$id,'liquidacion_estado'=>'PENDIENTE']);return['intento_id'=>$id,'monto'=>$amount,'checkout_url'=>$created['checkout_url'],'aviso'=>'Cobro real sujeto a comisiones; no afecta venta, caja, DTE ni stock'];}

    private function reconcileIntent(array $intent,string $providerId):void{$config=$this->requiredConfig((int)$intent['empresa_id'],(string)$intent['proveedor']);$status=PaymentGatewayFactory::fromConfig($config)->getPayment($providerId);if((string)$status['reference']!==''&&(string)$status['reference']!==(string)$intent['referencia'])throw new HttpException('Referencia de pago inconsistente',409);if((int)$status['amount']!==0&&(int)$status['amount']!==(int)$intent['monto'])throw new HttpException('Monto de pago inconsistente',409);$db=$this->payments->connection();try{$db->beginTransaction();$locked=$this->payments->intent((int)$intent['empresa_id'],(int)$intent['id'],true);if($locked===null)throw new HttpException('Intento no encontrado',404);$previous=(string)$locked['estado'];$new=(string)$status['status'];$this->payments->updateIntent((int)$locked['id'],['proveedor_id'=>(string)$status['provider_id'],'estado'=>$new,'provider_fee'=>$status['fee']??null,'merchant_net_amount'=>$status['net_amount']??null,'settlement_status'=>$status['settlement_status']??'NO_VERIFICABLE','expected_settlement_at'=>$status['expected_settlement_at']??null,'raw_status_json'=>json_encode($status['raw']??[],JSON_UNESCAPED_UNICODE),'ultimo_error'=>null]);if($new==='APROBADO'&&$previous!=='APROBADO')$this->applyApproved($locked);if((string)$locked['tipo']==='VERIFICACION'&&$new==='APROBADO')$this->payments->upsertVerification((int)$locked['empresa_id'],(string)$locked['proveedor'],['live_payment_verified_at'=>date('Y-m-d H:i:s'),'liquidacion_estado'=>$status['settlement_status']??'NO_VERIFICABLE']);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}
    private function applyApproved(array $intent):void{if($intent['reserva_id']===null)return;$r=$this->cerca->reservation((int)$intent['empresa_id'],(int)$intent['reserva_id'],true);if($r===null)throw new HttpException('Reserva asociada no encontrada',404);$paid=(int)$r['pagado']+(int)$intent['monto'];$balance=max(0,(int)$r['subtotal']-$paid);$state=$paid>0?'PAGO_CONFIRMADO':(string)$r['estado'];$s=$this->payments->connection()->prepare('UPDATE presencia_reservas SET pagado=:pagado,saldo_pendiente=:saldo,estado=:estado WHERE id=:id AND empresa_id=:empresa_id');$s->execute(['pagado'=>$paid,'saldo'=>$balance,'estado'=>$state,'id'=>$r['id'],'empresa_id'=>$r['empresa_id']]);$this->cerca->reservationEvent((int)$r['empresa_id'],(int)$r['id'],'PAGO_APROBADO',['intento_id'=>$intent['id'],'monto'=>$intent['monto'],'saldo'=>$balance]);}
    private function requiredConfig(int $empresaId,string $provider):array{$c=$this->payments->config($empresaId,$provider);if($c===null)throw new HttpException('Pasarela no configurada',422);if($provider==='MERCADOPAGO'&&!empty($c['token_expires_at'])&&strtotime((string)$c['token_expires_at'])<time()+300)$c=$this->refreshMercadoPago($c);return$c;}
    private function refreshMercadoPago(array $config):array{$refresh=!empty($config['refresh_token_cifrado'])?Crypto::decrypt((string)$config['refresh_token_cifrado']):'';if($refresh==='')throw new HttpException('La autorizacion Mercado Pago expiro; vuelve a conectar la cuenta',409);$clientId=trim((string)Env::get('MP_MARKETPLACE_CLIENT_ID',''));$secret=trim((string)Env::get('MP_MARKETPLACE_CLIENT_SECRET',''));if($clientId===''||$secret==='')throw new HttpException('OAuth Mercado Pago no configurado',503);$response=(new \Mypos\Support\GatewayHttpClient())->request('POST','https://api.mercadopago.com/oauth/token',['Accept: application/json','Content-Type: application/json'],json_encode(['client_id'=>$clientId,'client_secret'=>$secret,'grant_type'=>'refresh_token','refresh_token'=>$refresh],JSON_UNESCAPED_SLASHES));if($response['status']<200||$response['status']>=300||empty($response['body']['access_token']))throw new HttpException('No se pudo renovar Mercado Pago',502);$b=$response['body'];$this->payments->upsertConfig(['empresa_id'=>(int)$config['empresa_id'],'proveedor'=>'MERCADOPAGO','ambiente'=>$config['ambiente'],'credencial_publica'=>$config['credencial_publica'],'secreto_cifrado'=>null,'access_token_cifrado'=>Crypto::encrypt((string)$b['access_token']),'refresh_token_cifrado'=>!empty($b['refresh_token'])?Crypto::encrypt((string)$b['refresh_token']):$config['refresh_token_cifrado'],'token_expires_at'=>(new DateTimeImmutable('+'.(int)($b['expires_in']??21600).' seconds'))->format('Y-m-d H:i:s'),'merchant_id'=>$config['merchant_id'],'webhook_secret_cifrado'=>null,'activo'=>(int)$config['activo'],'orden'=>(int)$config['orden'],'metadata_json'=>$config['metadata_json']]);$updated=$this->payments->config((int)$config['empresa_id'],'MERCADOPAGO');if($updated===null)throw new HttpException('No se pudo renovar Mercado Pago',500);return$updated;}
    private function provider(string $p):string{$p=strtoupper(trim($p));if(!in_array($p,['FLOW','MERCADOPAGO'],true))throw new HttpException('Pasarela invalida',422);return$p;}
    private function flag(mixed $v):int{return filter_var($v,FILTER_VALIDATE_BOOLEAN)?1:0;}
    private function nullable(mixed $v,int $max):?string{$s=trim((string)$v);if($s==='')return null;if(strlen($s)>$max)throw new HttpException('Valor demasiado largo',422);return$s;}
}
