<?php

declare(strict_types=1);

namespace Mypos\Repositories;

use PDO;

final class OnlinePaymentRepository
{
    public function __construct(private readonly PDO $db){}
    public function connection():PDO{return$this->db;}
    public function config(int $empresaId,string $provider):?array{$s=$this->db->prepare('SELECT * FROM pasarelas_pago_config WHERE empresa_id=:empresa_id AND proveedor=:proveedor LIMIT 1');$s->execute(['empresa_id'=>$empresaId,'proveedor'=>$provider]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function activeConfigs(int $empresaId):array{$s=$this->db->prepare('SELECT proveedor,ambiente,merchant_id,activo,orden,metadata_json,updated_at FROM pasarelas_pago_config WHERE empresa_id=:empresa_id AND activo=1 ORDER BY orden,proveedor');$s->execute(['empresa_id'=>$empresaId]);return$s->fetchAll()?:[];}
    public function upsertConfig(array $d):int{$s=$this->db->prepare("INSERT INTO pasarelas_pago_config (empresa_id,proveedor,ambiente,credencial_publica,secreto_cifrado,access_token_cifrado,refresh_token_cifrado,token_expires_at,merchant_id,webhook_secret_cifrado,activo,orden,metadata_json) VALUES (:empresa_id,:proveedor,:ambiente,:credencial_publica,:secreto_cifrado,:access_token_cifrado,:refresh_token_cifrado,:token_expires_at,:merchant_id,:webhook_secret_cifrado,:activo,:orden,:metadata_json) ON DUPLICATE KEY UPDATE ambiente=VALUES(ambiente),credencial_publica=COALESCE(VALUES(credencial_publica),credencial_publica),secreto_cifrado=COALESCE(VALUES(secreto_cifrado),secreto_cifrado),access_token_cifrado=COALESCE(VALUES(access_token_cifrado),access_token_cifrado),refresh_token_cifrado=COALESCE(VALUES(refresh_token_cifrado),refresh_token_cifrado),token_expires_at=COALESCE(VALUES(token_expires_at),token_expires_at),merchant_id=VALUES(merchant_id),webhook_secret_cifrado=COALESCE(VALUES(webhook_secret_cifrado),webhook_secret_cifrado),activo=VALUES(activo),orden=VALUES(orden),metadata_json=VALUES(metadata_json),id=LAST_INSERT_ID(id)");$s->execute($d);return(int)$this->db->lastInsertId();}
    public function upsertVerification(int $empresaId,string $provider,array $changes):void{$allowed=['credenciales_estado','sandbox_estado','pago_real_intento_id','liquidacion_estado','credenciales_verified_at','sandbox_verified_at','live_payment_verified_at','settlement_verified_at','ultimo_error'];$params=['empresa_id'=>$empresaId,'proveedor'=>$provider];$keys=[];foreach($changes as$k=>$v){if(!in_array($k,$allowed,true))continue;$keys[]=$k;$params[$k]=$v;}if($keys===[])return;$sql="INSERT INTO pasarelas_verificaciones (empresa_id,proveedor,".implode(',',$keys).") VALUES (:empresa_id,:proveedor,".implode(',',array_map(fn($k)=>':'.$k,$keys)).") ON DUPLICATE KEY UPDATE ".implode(',',array_map(fn($k)=>$k.'=VALUES('.$k.')',$keys));$s=$this->db->prepare($sql);$s->execute($params);}
    public function verification(int $empresaId,string $provider):?array{$s=$this->db->prepare('SELECT * FROM pasarelas_verificaciones WHERE empresa_id=:empresa_id AND proveedor=:proveedor LIMIT 1');$s->execute(['empresa_id'=>$empresaId,'proveedor'=>$provider]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function insertIntent(array $d):int{$s=$this->db->prepare("INSERT INTO pagos_online_intentos (empresa_id,reserva_id,proveedor,tipo,idempotency_key,referencia,monto,estado) VALUES (:empresa_id,:reserva_id,:proveedor,:tipo,:idempotency_key,:referencia,:monto,'CREADO')");$s->execute($d);return(int)$this->db->lastInsertId();}
    public function intent(int $empresaId,int $id,bool $lock=false):?array{$s=$this->db->prepare('SELECT * FROM pagos_online_intentos WHERE empresa_id=:empresa_id AND id=:id LIMIT 1'.($lock?' FOR UPDATE':''));$s->execute(['empresa_id'=>$empresaId,'id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function intentByReference(string $reference,bool $lock=false):?array{$s=$this->db->prepare('SELECT * FROM pagos_online_intentos WHERE referencia=:referencia LIMIT 1'.($lock?' FOR UPDATE':''));$s->execute(['referencia'=>$reference]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function intentByProviderId(string $provider,string $providerId,bool $lock=false):?array{$s=$this->db->prepare('SELECT * FROM pagos_online_intentos WHERE proveedor=:proveedor AND proveedor_id=:proveedor_id LIMIT 1'.($lock?' FOR UPDATE':''));$s->execute(['proveedor'=>$provider,'proveedor_id'=>$providerId]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function intentByIdempotency(int $empresaId,string $key):?array{$s=$this->db->prepare('SELECT * FROM pagos_online_intentos WHERE empresa_id=:empresa_id AND idempotency_key=:idempotency_key LIMIT 1');$s->execute(['empresa_id'=>$empresaId,'idempotency_key'=>$key]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function updateIntent(int $id,array $d):void{$allowed=['proveedor_id','estado','checkout_url','provider_fee','merchant_net_amount','settlement_status','expected_settlement_at','settled_at','venta_id','consumed_at','raw_status_json','ultimo_error'];$sets=[];$params=['id'=>$id];foreach($d as$k=>$v){if(!in_array($k,$allowed,true))continue;$sets[]="$k=:$k";$params[$k]=$v;}if($sets===[])return;$s=$this->db->prepare('UPDATE pagos_online_intentos SET '.implode(',',$sets).' WHERE id=:id');$s->execute($params);}
    public function addEvent(string $provider,string $key,?int $intentId,array $payload):bool{$s=$this->db->prepare('INSERT IGNORE INTO pagos_online_eventos (proveedor,event_key,intento_id,payload_json) VALUES (:proveedor,:event_key,:intento_id,:payload_json)');$s->execute(['proveedor'=>$provider,'event_key'=>$key,'intento_id'=>$intentId,'payload_json'=>json_encode($payload,JSON_UNESCAPED_UNICODE)]);return$s->rowCount()===1;}
    public function markEventProcessed(string $provider,string $key):void{$s=$this->db->prepare('UPDATE pagos_online_eventos SET procesado_at=NOW() WHERE proveedor=:proveedor AND event_key=:event_key');$s->execute(['proveedor'=>$provider,'event_key'=>$key]);}
    public function pendingForReconcile(int $limit):array{$s=$this->db->query("SELECT * FROM pagos_online_intentos WHERE estado IN ('CREADO','PENDIENTE','APROBADO','REEMBOLSO_PENDIENTE') AND updated_at<DATE_SUB(NOW(),INTERVAL 2 MINUTE) ORDER BY updated_at LIMIT ".(int)$limit);return$s->fetchAll()?:[];}
    public function approvedForReservation(int $empresaId,int $reservationId):array{$s=$this->db->prepare("SELECT * FROM pagos_online_intentos WHERE empresa_id=:empresa_id AND reserva_id=:reserva_id AND estado='APROBADO' ORDER BY id");$s->execute(['empresa_id'=>$empresaId,'reserva_id'=>$reservationId]);return$s->fetchAll()?:[];}
    public function createOauthState(int $empresaId,int $userId,string $provider,string $hash,string $expires):void{$s=$this->db->prepare('INSERT INTO pasarelas_oauth_states (empresa_id,usuario_id,proveedor,state_hash,expires_at) VALUES (:empresa_id,:usuario_id,:proveedor,:state_hash,:expires_at)');$s->execute(['empresa_id'=>$empresaId,'usuario_id'=>$userId,'proveedor'=>$provider,'state_hash'=>$hash,'expires_at'=>$expires]);}
    public function consumeOauthState(string $provider,string $hash):?array{$s=$this->db->prepare('SELECT * FROM pasarelas_oauth_states WHERE proveedor=:proveedor AND state_hash=:state_hash AND used_at IS NULL AND expires_at>NOW() LIMIT 1 FOR UPDATE');$s->execute(['proveedor'=>$provider,'state_hash'=>$hash]);$r=$s->fetch();if(!is_array($r))return null;$u=$this->db->prepare('UPDATE pasarelas_oauth_states SET used_at=NOW() WHERE id=:id AND used_at IS NULL');$u->execute(['id'=>$r['id']]);return$u->rowCount()===1?$r:null;}
}
